import React from "react";
import { Box, Typography, Divider } from "@mui/material";

const sectionStyle = {
  mb: "var(--space-12)",
  "&:last-child": { mb: 0 },
};

const headingStyle = {
  mt: "var(--space-8)",
  mb: "var(--space-2)",
  fontWeight: 800,
  fontSize: "var(--text-xl)",
  color: "var(--primary-700)",
  scrollMarginTop: "var(--space-32)",
};

const IntellectualPropertySection: React.FC = () => {
  return (
    <>
      {/* Intellectual Property */}
      <Box id="intellectual-property" sx={sectionStyle}>
        <Typography component="h2" id="intellectual-property" sx={headingStyle}>
          Intellectual Property
        </Typography>
        <Typography sx={{ color: "var(--text-primary)", fontSize: "var(--text-base)" }}>
          All content, technology, and platform assets of Continuia—including but not limited to our clinical agent frameworks, UI designs, triage protocols, logos, documentation formats, and summary templates—are the intellectual property of Continuia Health Technologies and may not be used, copied, or reproduced without written permission.
          <br />
          <br />
          The clinical opinions generated by participating doctors remain the intellectual property of the clinician but are licensed to Continuia for platform operations, internal audits, and future educational purposes.
        </Typography>
      </Box>
      <Divider sx={{ mb: "var(--space-8)" }} />
    </>
  );
};
export default IntellectualPropertySection;
